### ISSUE TITLE
add docs on using `json -ga` option for stream processing json stream output from `triton * list -j`

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#102]
... because it isn't common (JSON stream instead of a single JSON array) and it differs from node-smartdc (e.g. `sdc-listmachines`).

**Comment by misterbisson** [comment]
I demo the following often (now converted to using `triton` instead of `sdc-listmachines`):

```
$ triton instance list -j | json -ga compute_node | sort | uniq -c
   1 44454c4c-4400-1046-8053-b5c04f383432
   1 44454c4c-4400-1047-8053-b5c04f383432
   1 44454c4c-4400-104d-8052-b5c04f383432
   1 44454c4c-4400-1050-8051-b5c04f383432
   1 44454c4c-4400-1052-8053-b5c04f383432
   1 44454c4c-4400-1056-8053-b5c04f383432
   1 44454c4c-4400-1057-804d-b5c04f383432
   1 44454c4c-4400-1057-8053-b5c04f383432
   1 44454c4c-4400-1059-804e-b5c04f383432
   1 44454c4c-5400-1043-8053-b5c04f383432
```

**Comment by trentm** [comment]
@misterbisson  Alternative:  `triton instance list -Ho compute_node | sort | uniq -c`

**Comment by doublerebel** [comment]
I'm conflicted. I prefer newline-delimited json coming from node, but streaming json is hard to sort unless I accumulate it.  So whereas before I could just pipe `sdc-list*****` into `jq`, now I have to pipe it into `json -g` and then `jq` to filter and sort it.

On the other hand, most of the filtering and sorting I need to do now is handled by `triton` + standard cli tools like `head/tail` and `awk`.

It would be great to filter `triton instance list` by `=~` as is possible with `triton image list`.  That's the only place I still need `json`+`jq`.

**Comment by trentm** [comment]
@doublerebel Thanks for the notes. Can't you process newline-separated JSON with `jq`? E.g.:

```
$ echo '{"foo": 1}
{"foo": 2}' | jq '.foo'
1
2
```

I don't know `jq` that well though, to know.

I agree that 'triton inst list' filtering with `=~` would be nice. Would you mind opening a feature request issue for that?

I suppose we could consider a '-J' (capital j) option that did strict JSON (with a note explaining that that could imply larger mem usage).  Generally I'd like to avoid adding lots of features for output formats.  Also, I'm going to hate myself and want the option help output have `-j, --json, -J` all on one line, but the option processing library doesn't support that automatically. ... :)

**Comment by doublerebel** [comment]
@trentm `jq` will filter each object individually, but since the stream is not a list it will not sort the objects.  `jq` doesn't have a concept of group-at-newline so I need another tool to do that.

Example:
```sh
$ sdc-listimages | jq "map(select(.name | contains(\"base-64\"))) | sort_by(.version)[-1]"
```
```js
{
  "id": "13f711f4-499f-11e6-8ea6-2b9fb858a619",
  "name": "base-64",
  "version": "16.2.0",
  "os": "smartos",
  ...
}
```
```sh
$ triton image list | jq "map(select(.name | contains(\"base-64\"))) | sort_by(.version)[-1]"
parse error: Invalid numeric literal at line 1, column 8
```

I understand wanting to standardize on a single format, I'm not sure what the complete answer is here.  Opening a feature request.
