### ISSUE TITLE
want `triton env --unset,-u` option emit env to unset relevant envvars

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#111]
`eval "$(triton env)"` nicely sets up my env. However, sometimes I want to clear my env of these vars. A good example is switching between a Triton Docker:

```
$ triton-select () { eval "$(triton env $1)"; }

$ triton-select east3b
$ docker info 2>/dev/null | grep Name
Name: us-east-3b
```

And, say, Docker for Mac:

```
$ triton-select -u
$ docker info 2>/dev/null | grep Name
Name: docker
```

**Comment by misterbisson** [comment]
Not saying we should support `--unset`, but I find `docker-machine env...` the best way to set my Docker vars for local use.

**Comment by trentm** [comment]
@misterbisson Uh, you have Triton docker's in `docker-machine`?

**Comment by trentm** [comment]
@misterbisson Also I find it interesting that the Docker for Windows/Mac beta do *not* put the local Docker Host VM in a `docker-machine ls`.

**Comment by misterbisson** [comment]
> you have Triton docker's in docker-machine?

No, but I switch to Triton using `triton env...` and to local with `docker-machine env...`
