### ISSUE TITLE
error messages from command line parsing should include command synopsis

### ISSUE THREAD

**Issue by rmustacc** [joyent/node-triton#113]
I was trying to figure out the right way to get the help message out of the triton cli commands. The following represent several wrong attempts:

```
rm@zanarkand ~ $ triton instance create
triton instance: error (Usage): incorrect number of args
rm@zanarkand ~ $ triton instance create help
triton instance: error (Usage): incorrect number of args
```

Given that the command has enough state to know that this is a usage error, it'd be really helpful if it actually included what the actual usage was, even if abbreviated. Other commands when given arguments that don't make sense will remind you of that usage.

An example would be:

```
rm@zanarkand ~ $ triton instance create help
triton instance: error: incorrect number of args
usage: triton instance create [<options>] IMAGE PACKAGE
```

**Comment by trentm** [comment]
Thought I had that already. I'll look.

**Comment by trentm** [comment]
Originally added in #5... which helped really only for `Usage` and `Option` errors on the first level of subcmds:

```
$ triton services -asdf
triton services: error (Option): unknown option: "-a" in "-asdf" group

Usage:
     triton services

Options:
    -h, --help                Show this help.

  Output options:
    -H                        Omit table header row.
    -o field1,...             Specify fields (columns) to output.
    -s field1,...             Sort on the given fields. Default is "name".
    -j, --json                JSON output.
```

Even that sucks. Two problems here:

1. The multi-level subcmd stuff was added to node-cmdln (the lib triton is using) *for* triton. One part that lagged was totally clean handling for help output for sub-subcmds. So, while in this case the top-level code that is handling printing out the error with code `Usage` or `Option`, it has lost some of the state. As well, I'd need to do some (backward incompat) changes to node-cmdln in subcmd help handling here.

2. Currently node-cmdln's API for subcmds doesn't separate the full help output from just the usage/synopsis. I think what we want for error output here is just that short synopsis, else the error message itself would get lost.

---

Notes to self for eventual node-cmdln work on this:

- Change away from using the help string for this. Add an API to subcmds to provide a short (typically a single line) synopsis/usage.
- For dispatch errors (where we currently pass back the `subcmd` string), change to returning the subcmd
function itself -- including the subsubcmd if the error originated there. Then top-level error printing code can just use that synopsis string on the given subsubcmd (or top-level Cmdln object if error was at that level).

**Comment by trentm** [comment]
This is in triton@4.13.0 now.
