### ISSUE TITLE
unknown command warning gives duplicate information

### ISSUE THREAD

**Issue by rmustacc** [joyent/node-triton#114]
Consider the following error message:

```
rm@zanarkand ~ $ triton instance destroy 0aab1323
triton instance: error (UnknownCommand): unknown command: "destroy"
```

Note how we get told that there's an unknown command destroy, but then we're also told in parens the `(UnknownCommand)` portion. It almost looks like that's some kind of error class. I think that a lot of the error messages would be clearer without that including that bit in parens. The prose should make it clear what the error is and why it occurred. If it's not, then error descriptions should be improved.

**Comment by trentm** [comment]
Respectfully disagree. There are a number of error codes in `triton` and in general those are shown to the user because (a) they then make it back to the developer/bug tracker when issues are reported/questions asked and/or (b) the user hitting that error has a code to grep for in the source.

The cost is a bit more noise on the command line.

Happy to discuss more later if you like.

**Comment by askfongjojo** [comment]
I'd also add that the error code is for a program to use, not a human being, for error handling logic. If we have error number, we can go without that short code.

**Comment by rmustacc** [comment]
@trentm Fair enough. I realize that this is something where there's different opinions. I mostly mentioned that because it stands out as very different from pretty much all the other utilities I use on a regular basis. But at the end of the day, it's just noise. But for what it's worth, I tried to see if these were actually in the source before reporting this, but just cloning the repo and searching for this one turned nothing up. Maybe because it's in a library or some dep.

@askfongjojo I'm not sure I follow. In general, if someone's trying to use triton programmatically, then they'd either want to use an underlying library or use some other interface such that they don't have to parse free-form text.

**Comment by lloydde** [comment]
I had the same thought as @rmustacc when I saw this output. It looks sophomoric. The grep argument doesn't seem particularly strong. Good prose trumps. Think of your casual user.

**Comment by rmustacc** [comment]
I think we had different thoughts. I can at least understand where the grep style argument comes from. Reflecting on it, I just do the mental transformation from error message to UNIX errno rather often. But if I was working with something that had a different set of errors and was trying to root cause what happened and why, then doing that transformation is the very first step I would do.

In this case, I did grep for it actually. It just turns out I forgot to install all the deps. Certainly when I have all of illumos in cscope, looking for places that errors turn up or where they're generated is important.
