### ISSUE TITLE
`triton -r,--role ROLE ...` to be able to take up an RBAC role

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#120]
With current Triton RBAC (v1) if a subuser is a member of a role (i.e. in `role.members`), but not default member (i.e. not in `role.default_members`), then requests needing that role need to explicitly take it up. Per the cloudapi docs (https://apidocs.joyent.com/cloudapi/#rules-definition-for-access-control) this is done via the "?as-role=ROLE,.." query param on requests.

We should have a `triton -r,--role=ROLE ...` option for this.

(Eventually it might be nice to have support for this in the profile, but I might not do that on this issue.)

**Comment by AlainODea** [comment]
👍  thanks!

**Comment by trentm** [comment]
This is in triton@4.12.0.  @AlainODea let me know if this doesn't fix the case you had.

**Comment by AlainODea** [comment]
It works if I use a top-level account with a role, but not if I use a sub-user with a role.

TopLevelAccount profile:

```bash
$ triton profile get
name: TopLevelAccount
account: TopLevelAccount
curr: true
insecure: true
keyId: ea:8d:15:76:90:ca:84:96:ee:f2:83:9a:ed:06:19:e2
url: https://us-sw-1.example.com
```

hostdiscovery profile:

```bash
$ triton profile get hostdiscovery
name: hostdiscovery
account: TopLevelAccount
curr: false
insecure: true
keyId: ea:8d:15:76:90:ca:84:96:ee:f2:83:9a:ed:06:19:e2
url: https://us-sw-1.example.com
user: hostdiscovery
```

hostdiscovery RBAC role:

```bash
$ triton rbac role hostdiscovery
id: c289e20e-d32f-abcd-8e40-80868cb2cadd
name: hostdiscovery
default_members: hostdiscovery
members: hostdiscovery
policies: hostdiscovery
```

hostdiscovery RBAC policy:

```bash
$ triton rbac policy hostdiscovery
name: hostdiscovery
id: 093a18b4-b454-cf7e-b14a-c7f9db72aef2
description: Host discovery access
rules:
    CAN *
    CAN listmachines
```

Using the hostdiscovery role with the hostdiscovery sub-user fails:

```bash
$ triton -p hostdiscovery -r hostdiscovery instance list -o primaryIp
triton instance: error: first of 1 error: You do not have permission to access /TopLevelAccount/images (listimages)
```

Using no role with the hostdiscovery sub-user fails (expected based on IRC conversation):

```bash
$ triton -p hostdiscovery instance list -o primaryIp
triton instance: error: first of 1 error: You do not have permission to access /TopLevelAccount/images (listimages)
```

Using the hostdiscovery role with the TopLevelAccount profile works:

```bash
$ triton -r hostdiscovery instance list -o primaryIp
PRIMARYIP
192.168...
192.168...
```

Using no role with the TopLevelAccount profile works:

```bash
$ triton instance list -o primaryIp
PRIMARYIP
192.168...
192.168...
```

The TopLevelAccount has no RBAC enforced so I'm not sure whether the role is being applied.

This is a private cloud deployment of Triton.  Do I need a certain version on my HN to support RBAC?

**Comment by trentm** [comment]
@AlainODea RBAC authz (e.g. the role info) isn't used for top-level account accesses, so that's a red herring.

I have a guess: `triton instance list` *also* attempts to list images so that it can show image name@version for the image UUIDs on a given instance. It looks like that one is failing. Do you role-tag "/TopLevelAccount/images"?  E.g. what is the output of this:

```
triton rbac role-tags /TopLevelAccount/images
```

?

**Comment by AlainODea** [comment]
Ah okay.

```bash
$ triton rbac role-tags /TopLevelAccount/images
$
```

No output.  No tags.

Subsequently I now have it working. @trentm you are awesome 💯 

The fix is:

```bash
$ triton rbac role-tags -a hostdiscovery /TopLevelAccount/images
```

Now the request with a profile works:

```bash
$ triton -p hostdiscovery instance list -o primaryIp
PRIMARYIP
192.168...
192.168...
```

That is dependent on Sub-User hostdiscovery being in default_members of Role hostdiscovery (understandably given the RBACv1 design).

Removing Sub-User hostdiscovery from default-members to restore a state achievable in Roles creating in AdminUI:

```bash
$ triton rbac role hostdiscovery
id: c289e20e-d32f-41de-8e40-80868cb2cadd
name: hostdiscovery
default_members: hostdiscovery
members: hostdiscovery
policies: hostdiscovery
$ triton rbac role hostdiscovery -e # in $EDITOR set default_members to blank
$ triton rbac role hostdiscovery
id: c289e20e-d32f-41de-8e40-80868cb2cadd
name: hostdiscovery
default_members:
members: hostdiscovery
policies: hostdiscovery
```

Leads to the original (expected as per our discussion and the RBACv1 design) auth error:

```bash
$ triton -p hostdiscovery instance list -o primaryIp
triton instance: error (NotAuthorized): You do not have permission to access /TopLevelAccount/machines (listmachines)
```

Running the using with an assumed role (as now supported in 4.1.0+) works:

```bash
$ triton -p hostdiscovery -r hostdiscovery instance list -o primaryIp
192.168...
192.168...
```

Rock on :)

**Comment by AlainODea** [comment]
I was able to carve down the Policy hostdiscovery using `triton rbac policy hostdiscovery -e` as well (removing CAN *):

```
$ triton rbac policy hostdiscovery
name: hostdiscovery
id: 093a18b4-b454-cf7e-b14a-c7f9db72aef2
description: Host discovery access
rules:
    CAN listmachines
```

This is a *really* nice CLI experience. Well done.

**Comment by trentm** [comment]
^^ @AlainODea  Updated 'triton instance list' to not fail if the user doesn't have ListImages rights (i.e. the thing you hit).

**Comment by AlainODea** [comment]
Neat! I like it.  Tested to work as described.  Thanks again @trentm :)
