### ISSUE TITLE
`triton reboot --wait INST` doesn't wait

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#129]
...at least it doesn't wait until it has started again. That is my assumption of the intention of --wait there.

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/880/

**Comment by trentm** [comment]
As said on the CR, that solution won't work.

The current code is broken that it can get a 'running' state before the instance has rebooted, which is wrong.

The CR above is wrong because the polling for the instance 'state' might never see the 'stopped' or 'stopping' states if the reboot is quick.

While not perfect, here is what might be a reasonably workable solution for now:  Use the MachineAudit endpoint (https://apidocs.joyent.com/cloudapi/#MachineAudit  aka `triton instance audit INST`) and watch for a new 'action=reboot' audit entry after the reboot is issued. An example:

While running `triton reboot a749a181-cb8d-4239-b638-586cf9f0455f` I was running this in the background:

```
$ while true; do echo ''; triton inst get a749a181-cb8d-4239-b638-586cf9f0455f | json state; triton inst audit a749a181-cb8d-4239-b638-586cf9f0455f; triton inst get a749a181-cb8d-4239-b638-586cf9f0455f | json state; sleep 0.5; done

running
SHORTID   TIME                      ACTION     SUCCESS
a749a181  2016-11-17T23:19:32.157Z  provision  yes
running

...

running
SHORTID   TIME                      ACTION     SUCCESS
a749a181  2016-11-17T23:19:32.157Z  provision  yes
running

running
SHORTID   TIME                      ACTION     SUCCESS
a749a181  2016-11-17T23:19:32.157Z  provision  yes
a749a181  2016-11-23T00:00:36.135Z  reboot     yes
running
```

Note there that a reboot happened without 'triton isntance get INST' ever seeing anything but a 'running' state.

Using this technique the implementation would be something like:

1. get MachineAudit on the INST to get the audit entries before rebooting
2. send the RebootMachine request
3. poll MachineAudit for a new 'reboot' entry, and report success/failure based on the 'success' value from that


Limitations: This is still imperfect as there is ambiguity if two callers are rebooting that instance at the same time. Better would be if RebootMachine returned a handle/id in its response that could be used to identify a particular entry in MachineAudit. I've opened https://smartos.org/bugview/PUBAPI-1347 to do that eventually.

**Comment by trentm** [comment]
alternative CR: https://cr.joyent.us/#/c/1473

**Comment by trentm** [comment]
@YangYong3 Thanks for the initial stab at this.
