### ISSUE TITLE
"triton key list" does not return the key value, whereas "sdc-listkeys" does

### ISSUE THREAD

**Issue by khangngu** [joyent/node-triton#132]
$ triton key list
FINGERPRINT                                      NAME
c5:48:5a:7f:c0:9e:a5:b8:ef:a3:43:1b:fa:94:b9:61  khangtest

whereas

$ sdc-listkeys
[
  {
    "name": "khangtest",
    "fingerprint": "c5:48:5a:7f:c0:9e:a5:b8:ef:a3:43:1b:fa:94:b9:61",
    "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr1bonw13MJ96oRY77ROiNwdDvTfw4P3sQiTvmcn4aB73Gij87xQR3R0cLgbsmtxiRPCHQLVWJBRlDXa5uY08EmYMx/EcZu+Yr9Z5Y7O9oXvUYx9WKZThB1zem1FOg6pUDLa09gNDW9wyxGyfq0mf7NmHysitkEQOM7uscEVGppEPN8lrjYYq2goPvVISIpCK6/FiUO+yw47DIIjEEA2OL9UZpAcdZwHJbvvF+hXl13SMdeN45lYl/2NX/KxjH/WJ7DSIzhvlXzN1TwpAbsQ16I+5+/A/mMYHtlz63aJ7vNE0gnN+6pCalxsYh+pJLIkMl3XcVcbe5hCKPppYpKX8T khang.nguyen@joyadmins-MacBook-Pro.local"
  }
]

**Comment by chorrell** [comment]
I think the intention is to make the values available via `triton key get NAME`.

For example `triton key get khangtest` would return:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr1bonw13MJ96oRY77ROiNwdDvTfw4P3sQiTvmcn4aB73Gij87xQR3R0cLgbsmtxiRPCHQLVWJBRlDXa5uY08EmYMx/EcZu+Yr9Z5Y7O9oXvUYx9WKZThB1zem1FOg6pUDLa09gNDW9wyxGyfq0mf7NmHysitkEQOM7uscEVGppEPN8lrjYYq2goPvVISIpCK6/FiUO+yw47DIIjEEA2OL9UZpAcdZwHJbvvF+hXl13SMdeN45lYl/2NX/KxjH/WJ7DSIzhvlXzN1TwpAbsQ16I+5+/A/mMYHtlz63aJ7vNE0gnN+6pCalxsYh+pJLIkMl3XcVcbe5hCKPppYpKX8T khang.nguyen@joyadmins-MacBook-Pro.local
```

**Comment by chorrell** [comment]
Also, if you want access to the json output (which includes the "key" value), you can use the `-j` flag:

```
triton key list -j
```

**Comment by kusor** [comment]
`node-triton` and `node-smartdc` are not mean to be compatible near feature equal. Use `triton key get $key_name`.
