### ISSUE TITLE
node-triton should include ability to reprovision a machine

### ISSUE THREAD

**Issue by jussisallinen** [joyent/node-triton#141]
Currently node-triton is missing ability to reprovision a machine to a current or newer image version.

-Is there a technical reasoning behind this or is it just oversight?

node-smartdc is also missing this feature:
[node-smartdc should have sdc-reprovisionmachine in the toolset #79](https://github.com/joyent/node-smartdc/issues/79)

Reprovisioning is a useful feature when doing rolling upgrades and not wanting to spin up another instance for upgrades (ie. the IP needs to stay the same without too much hassle or need to actually rm the instance for image version bump).

VMAPI client library seems to include the possibility for doing a reprovision and reprovision is currently possible through the WebUI:
https://github.com/joyent/node-sdc-clients/blob/master/lib/vmapi.js#L896

My particular use case is using reprovision for going from ie. 16.1.0 to 16.3.0.

**Comment by bahamat** [comment]
node-smartdc and node-triton use CloudAPI, not any of the internal APIs.

Reprovision isn't an exposed interface in CloudAPI. See https://github.com/joyent/sdc-cloudapi/blob/master/docs/index.md

Also joyent/node-smartdc#79.

**Comment by trentm** [comment]
I'm going to close this for now. Happy to re-open it when Cloud API supports reprovisioning.

**Comment by blackwood821** [comment]
I would love to see this feature in CloudAPI

**Comment by jasonbking** [comment]
Unfortunately a reprovision can fail for several reasons, and all of them require operator intervention to clean things up before the instance can be restarted, so it's not something we've ever opted to expose as a 'self service' interface (e.g. CloudAPI).
