### ISSUE TITLE
`triton instance rename --wait`

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#146]
`triton instance rename` was added in https://github.com/joyent/node-triton/issues/64
(CR https://cr.joyent.us/#/c/828/). However RenameMachine is async, so it would be nice to add a '-w,--wait' option as is done for some other `triton` commands.

A relevant comment from the CR above:

> "wait" support: Updating an instance name is asynchronous -- the actual name change is done in an internal job that updates data on the instance living on its compute node (server).  
> 
> Unfortunately, cloudapi doesn't currently support a great method for waiting for that to complete.
> Renames *do* show up in MachineAudit ('triton inst audit INST') but the RenameMachine endpoint doesn't return a handle/id to indicate which MachineAudit entry is related, so there is a race there.
> 
> The only reasonable way to wait for completion is to poll on GetMachine to wait for the name change... with the potential that that could have a race if the name is changed back and forth in the polling gap.
> 
> See TritonApi.prototype.waitForInstanceTagChanges for something to copy -- perhaps adding a "waitForInstanceNameChange". It should be simpler than "waitForInstanceTagChanges". If you want help with this, I'm happy to help.
> 
> If you like, we could do a first pass at 'triton inst rename' *without* wait support. Then add wait support later.
>

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/961/

**Comment by trentm** [comment]
merged now. This will be in triton@5.0.0 when that is released.
