### ISSUE TITLE
fallback to ~/.ssh during docker profile creation

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-triton#150]
Followup to #108 

When we find a key fingerprint in both ~/.ssh and ssh-agent we prefer the one in the agent.  This is basically the expectation of using an agent to begin with (no repeat password entry), but when creating the docker cert the local `triton` command needs the private key.  The agent can't/won't provide a private key and we currently fail with something along the lines of:
```
triton profile docker-setup: error (Setup): could not obtain SSH private key for keypair with fingerprint 
```

In the common case of working on a local workstation (no agent forwarding) we could "fallback" to trying to read out of ~/.ssh.

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1545/
