### ISSUE TITLE
consider alternative ways of handling the docker cert

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-triton#151]
When creating a TLS cert for docker we now issue this warning:

```
WARNING: Docker uses TLS-based authentication with a different security model
from SSH keys. As a result, the Docker client cannot currently support
encrypted (password protected) keys or SSH agents. If you continue, the
Triton CLI will attempt to format a copy of your SSH *private* key as an
unencrypted TLS cert and place the copy in ~/.triton/docker for use by the
Docker client.
```

One partial mitigation would be to create a new (throwaway?) SSH key, add it to the account, and then derive the TLS cert from that key.  This would still leave a mismatch in expectations (there is a way to interact with Triton via unencrypted files even if everything in ~/.ssh is encrypted) but the key at risk is not one used for other systems or services.

In principle (with server-side changes) it may be possible to limit the access of this "docker key" so that it can only interact with the Docker API.

**Comment by bahamat** [comment]
Fixed in 5734123
