### ISSUE TITLE
support resizing of instances

### ISSUE THREAD

**Issue by andrew-wharton** [joyent/node-triton#157]
Support for this endpoint https://apidocs.joyent.com/cloudapi/#ResizeMachine seems to be missing. I'd be willing to put together a pull request if needed, as we were hoping to use this.

Looking through the source, changes that would be needed are:

- Update /lib/cloudapi2.js - add the resize endpoint as CloudApi.prototype.resizeMachine using basically the same logic as CloudApi.prototype.renameMachine
- Update /lib/tritonapi.js - wire the new resizeMachine CloudAPI method into TritonApi.prototype.resizeInstance
- Add /lib/do_instance/do_resize.js - add a new file with the function to call through to the TritonAPI resizeInstance method.
- Update /lib/do_instance/index.js - add the new do_resize function to the InstanceCLI prototype and add it to the helpSubcmds.

I think that's about it. Let me know if you're happy to move forward with this, or if there's a reason why it's not included.

**Comment by bahamat** [comment]
@andrew-wharton There's no reason in particular that anything has been left out.
If you're interested, check out our [contributing guidelines](https://github.com/joyent/triton/blob/master/CONTRIBUTING.md).

**Comment by andrew-wharton** [comment]
Thanks, been away on holidays over the Christmas break, but I'll move forward with this now.

**Comment by andrew-wharton** [comment]
@bahamat I've got my [changes](https://github.com/joyent/node-triton/compare/master...andrew-wharton:master) ready and tried to push them to gerrit, but got an error.

```
andrew:node-triton andrew$ git push cr HEAD:refs/for/master
...
[remote rejected] HEAD -> refs/for/master (you are not allowed to upload merges)
```

I think this is because I pulled and merged in the latest changes from joyent/node-triton before finishing up my changes (I probably should have rebased when pulling).

Any suggestions for how to proceed?

**Comment by rmustacc** [comment]
@andrew-wharton what does `git remote show -n cr` output there?

**Comment by rmustacc** [comment]
Sorry, I misread with the previous comment. The simplest thing would be to rework your local branch to end up rebasing. One way to do this would be to checkout the commit before you did the git pull via git reflog. Then do a git pull --rebase.

**Comment by andrew-wharton** [comment]
@rmustacc Great, thanks! I'll give this a go tonight and get back to you if I still have problems.

**Comment by andrew-wharton** [comment]
@rmustacc 

So I rebased and then added back my changes, and pushed to cr.joyent.us, but got back a whole bunch of change sets (https://cr.joyent.us/1411-1418). Guess I needed to squash them into a single commit before pushing.

So then I went and squashed them (and made a small fix) and pushed again to refs/changes/1418 and abandoned the other changes in the Gerrit UI.

I feel like the changes need a little explanation. The main changes I made are as follows:

- Update /lib/cloudapi2.js - add the resize endpoint as CloudApi.prototype.resizeMachine
- Update /lib/tritonapi.js - wire the new resizeMachine CloudAPI method into TritonApi.prototype.resizeInstance
    - I also wanted to reuse the '_waitForInstanceName' functionality, so I renamed it to '_waitForInstanceUpdate' and abstracted the check to a function which you pass in. Hope this is OK.
    - I also added a step to normalise the package name/shortId/id to the id. This is expected I think.
- Add /lib/do_instance/do_resize.js - add a new file with the function to call through to the TritonAPI resizeInstance method.
    - This was pretty much boilerplate code, nothing interesting here
- Update /lib/do_instance/index.js - add the new do_resize function to the InstanceCLI prototype and add it to the helpSubcmds.

I also added an integration test for the resize command, which required also adding a helper function to grab the package name to resize to. I wasn't entirely sure what to do here, as it kind of needed additional config information, just like the package, so I also updated the README and the test.config.sample. When testing that the package resize was applied, we only the the package name back from getInstance, so it has to be the package name which is given in the config (can't be a package id). I hope this is OK, it was a bit outside the scope of the changes I was originally planning, but seemed necessary to me.

Also I wasn't able to run the integration tests as I was hitting rate limiting from the Joyent API, but I've tried to be careful and looked over them a few times, so they should work.

Hopefully after all this I haven't made too big a mess on you Gerrit server. Trying to use git outside my normal workflow, I feel like a drunk guy stumbling all over the place breaking stuff...

**Comment by andrew-wharton** [comment]
Just a follow up. I noticed on https://cr.joyent.us/#/c/1418/ my changes have a merge conflict.

I'm not entirely sure of the process I need to follow to have the changes reviewed and integrated, but if there's anything I need to do on my end, just let me know and I'll sort it out ASAP.

**Comment by rmustacc** [comment]
We're getting some folks to review it. Don't worry about the merge conflict, we'll end up rebasing the change before it lands.

**Comment by andrew-wharton** [comment]
Great, thanks!

**Comment by trentm** [comment]
@andrew-wharton Thanks! Just started looking.  SOrry about the delay, I missed the traffic here.

FWIW, I wrote a `grr` tool to help working with our Gerrit at cr.joyent.us: https://github.com/joyent/grr   It helps with things like squashing N commits in a feature branch to push to a Gerrit CR, and remembering which CR is being used to be able to update it with subsequent commits on that feature branch. However, it is totally optional.

**Comment by trentm** [comment]
Merged https://cr.joyent.us/#/c/1418/
Thanks @andrew-wharton!

Note that it might be a little while before I get a new release out (it'll be version 5.0.0; and it is past due)

**Comment by andrew-wharton** [comment]
Thanks @trentm, good to hear.
