### ISSUE TITLE
tritonapi image cache never expires

### ISSUE THREAD

**Issue by dillona** [joyent/node-triton#158]
My "triton ls" command returns bogus output for some images like the following:
SHORTID   NAME      IMG                STATE    FLAGS  AGE
8beae1be  8beae1be  8879c758           running  -      3d
557cb9a6  KVM       b8a4ba09           running  K      1d

I've tracked down the issue to being a bad image cache. It appears to
never expire.
This means that any time I launch a container/VM with a recent image,
the name does not show up properly.

I proposed on sdc-discuss that the correct behavior was to expire the cached JSON file based on the stat() modified time, and I have implemented this change.

**Comment by dillona** [comment]
I don't think I can actually assign this to myself.

I hope it's alright that I'm going to put up a changelist for review anyway.

**Comment by bahamat** [comment]
@dillona The contributing guidelines are here: https://github.com/joyent/triton/blob/master/CONTRIBUTING.md
