### ISSUE TITLE
see fix for joyent/node-sshpk#22 before release

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#166]
We should hold up a triton@5 release until there is a fix for joyent/node-sshpk#22 else "it means docker-setup currently breaks for anyone with a _ in their username" (quoting @arekinath).

**Comment by arekinath** [comment]
Fix released in sshpk 1.10.2

**Comment by trentm** [comment]
A symptom of this issue is that after a `triton profile docker-setup` and attempt to use docker 1.13:

```
$ docker --version
Could not load X509 key pair: asn1: syntax error: PrintableString contains invalid character. Make sure the key is not encrypted
```

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1407/
