### ISSUE TITLE
`triton rbac ...` broken by #108

### ISSUE THREAD

**Issue by YangYong3** [joyent/node-triton#169]
after add 'common.cliSetupTritonApi '... it's not working 

$  bin/triton rbac users
-> triton rbac: error: Cannot read property 'listUsers' of undefined

also keys, policies ... about rbac

**Comment by trentm** [comment]
@yangyong3 I see 3 open CRs for this change:
- https://cr.joyent.us/#/c/1421/
- https://cr.joyent.us/#/c/1420/
- https://cr.joyent.us/#/c/1438/

Should two of those be abandoned?

**Comment by YangYong3** [comment]
thanks. i did abandon that

**Comment by trentm** [comment]
triton@7.1.1 tagged and published with this change.
