### ISSUE TITLE
'triton profile create' and 'triton profile docker-setup' need a non-interactive option

### ISSUE THREAD

**Issue by paulleduc** [joyent/node-triton#182]
We are trying to implement automatic Triton deployment through the Docker CLI using docker-compose, which works fine when setting up your Triton profile (and docker-setup) manually. But what are our options if using a service like Travis CI to perform the docker-compose commands? The machines in Travis CI exist only as long as the build runs.

With the last version of this module we were able to hack together a work-around for avoiding the input prompts when running "triton profile create". That was to simply write the ~/.triton/profiles.d/profile.json file ourselves and run "triton profile docker-setup" afterwards. Now though, the docker-setup command prompts with the following:

> WARNING: Docker uses authentication via client TLS certificates that do not
> support encrypted (passphrase protected) keys or SSH agents. If you
> continue,this profile setup will attempt to write a copy of your SSH private
> key formatted as an unencrypted TLS certificate in "~/.triton/docker" for use
> by the Docker client.
> 
> Continue? [y/n]

Attempts to skip the above prompt using commands like "yes" have failed.

Any plans for no-prompt support for setting up Triton profiles or is there a better way I'm not seeing?

**Comment by trentm** [comment]
@paulleduc Sorry about that. I'll add a '-y' option to skip that prompt. (For other watching, this was broken in the triton@5.0.0 release.

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1566/

**Comment by trentm** [comment]
triton@5.1.0 published with the fix.
