### ISSUE TITLE
Exception when using current docker client

### ISSUE THREAD

**Issue by geek** [joyent/node-triton#190]
We should remove the semver check for the docker client: https://github.com/joyent/node-triton/blob/a3071585aa8b36bded88fa1860332977280b0537/lib/do_profile/profilecommon.js#L462

```
$ docker -v
Docker version 17.03.0-ce, build 60ccb22
```

Creating a new profile with the latest docker version results in the following exception

```
Setting up profile "us-east-1" to use Docker.
/Users/USER/.nvm/versions/node/v7.3.0/lib/node_modules/triton/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 17.03.0-ce
    at new SemVer (/Users/USER.nvm/versions/node/v7.3.0/lib/node_modules/triton/node_modules/semver/semver.js:293:11)
    at compare (/Users/USER/.nvm/versions/node/v7.3.0/lib/node_modules/triton/node_modules/semver/semver.js:566:10)
    at Function.gte (/Users/USER/.nvm/versions/node/v7.3.0/lib/node_modules/triton/node_modules/semver/semver.js:615:10)
    at Object.writeSetupJson [as func] (/Users/USER/.nvm/versions/node/v7.3.0/lib/node_modules/triton/lib/do_profile/profilecommon.js:462:31)
    at Immediate.<anonymous> (/Users/USER/.nvm/versions/node/v7.3.0/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:213:20)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by misterbisson** [comment]
The check _was_ needed to determine which env vars to set, but that change was around 1.8 or so and might not be needed anymore.

**Comment by KodyKantor** [comment]
I'll take this. I'll see what is still needed from this functionality, and how to fix (or bypass) this issue.

**Comment by KodyKantor** [comment]
Docker no longer checks for the deprecated DOCKER_CLIENT_TIMEOUT env var: 
https://github.com/docker/compose/pull/3705

My proposal is to remove this logic from the node-triton code, and just set both env vars. The users who will see the warning are running compose versions 1.5.0 to 1.8.0. That's November 2015 to August 2016.

Thoughts? Is there any harm in setting an unused environment variable?

**Comment by geek** [comment]
@KodyKantor agreed. Looks like a good solution.

**Comment by cburroughs** [comment]
Per the comment block, setting both variables appears to result in annoying messages from one of the docker commands.  I think the least invasive change would be to lob off the non-semver suffix before passing it along.  @KodyKantor If you take a stab at this, feel free to add me as a reviewer.

**Comment by KodyKantor** [comment]
I actually am of the mind that we should stop using semver. Docker doesn't follow semantic versioning, and it never has. In this code we're actually using semver to do a string comparison. Since Docker doesn't follow semver, it seems reasonable to not use semver to do a string comparison. Editing the version string will most likely result in confusing behavior if/when Docker either changes their versioning scheme again, or changes the version to be equal to something we've edited (i.e. we change 17.03.0 -> 17.3.0, and then docker releases a *real* version 17.3.0).

If we're using semver to ensure that Docker follows semantic versioning (they don't), we should keep semver in there. If we're using semver to do a string comparison, we should probably throw out semver.

As an aside, Docker stopped emitting the warning message as of compose v1.8.0

**Comment by trentm** [comment]
The semver module was just used as a convenience to do check if the current `docker` client version was greater than or equal to 1.9 -- not so much an assertion that Docker versions follow the spirit of semver.

> My [@KodyKantor's] proposal is to remove this logic from the node-triton code, and just set both env vars. The users who will see the warning are running compose versions 1.5.0 to 1.8.0.

Compose 1.9.0 was released Nov 15, 2016. That's four months ago, which isn't a huge time for some users to upgrade. We are just talking about a warning message though, so perhaps if older Compose usage is low we would be fine dropping the smarts here. I was going to say "+1 to dropping the version checking logic", but I checked Compose usage against our Docker endpoints in the Triton Public Cloud in Feb 2017, and Compose 1.8 usage isn't insignificant:

Compose 1.8 is ~8% of "docker-compose" user-agent hits:

       5.3%  docker-compose/1.11
       7.9%  docker-compose/1.9
       8.5%  docker-compose/1.8
      78.3%  docker-compose/1.10

And Compose 1.8 is ~3.3% of all sdc-docker requests.

Given that, I think I'd prefer to not drop the version checking logic *yet*.
Instead I think we can easily get it to just not break on surprising version
schemes from the docker client.

**Comment by trentm** [comment]
I'll follow up with code suggestions on @marktrem's CR https://cr.joyent.us/#/c/1667/

**Comment by marctrem** [comment]
Hey, I unfortunately created a new change https://cr.joyent.us/#/c/1680/ .
Please excuse me, I am new to Gerrit. Going to update the change properly next time.

**Comment by trentm** [comment]
@marctrem No problem at all!  Gerrit definitely has a learning curve. If it helps you, I wrote a `grr` tool (https://github.com/joyent/grr) to help with working on a change in a local feature branch and creating/updating a cr.joyent.us CR. Totally optional tho.

**Comment by trentm** [comment]
I moved it back (with an indentation tweak) to https://cr.joyent.us/#/c/1667

@KodyKantor Care to comment?

**Comment by geek** [comment]
@trentm LGTM. 

We should check the usage data of people using older versions of docker and their version of the triton cli. It will be useful to measure how quickly each of the different docker version segments upgrade their triton cli... if no one in the version 1.8 segment upgrade their triton cli then we will likely be safe to drop the semver check and warning.

**Comment by trentm** [comment]
Fixed. This'll be in triton@5.1.1 (later today).
