### ISSUE TITLE
want `triton profile cmon-setup` command

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#235]
Questions:

1. What's the ux?
    * `triton cmon`?
    * `triton metrics`?
    * `cmon metrics`?
    * Does discovery need to be exposed, since `triton` already lists instances?
2. Output?
    * just dump metrics?
    * [triton-top](/richardkiene/triton-top)?
    * triton-top, with option to dump raw metrics?
    * something else?

**Comment by trentm** [comment]
@richardkiene poke   Thoughts here?

**Comment by trentm** [comment]
I don't know what would be serve "I just want to use CMON a bit" people and "I want to hook up my instances et al to a prometheus or related metrics server" people.

**Comment by bahamat** [comment]
FWIW, my interest in it was just to be able to dump metrics to verify that cmon was working properly, and that my local configuration (i.e., certs) worked.

**Comment by arekinath** [comment]
Bringing this back up: I think what we should do is a `triton profile cmon-setup` command like `docker-setup`, which (now that CMON supports non-self-signed certs like Docker does) generates you a certificate and fresh key and an example `prometheus.yml` file showing how to use the discovery plugin with it.

Not that many people would probably use the example `prometheus.yml` exactly as we spit it out, but it should contain enough that you *can*, I think.

I think the command should take a subdirectory name as an argument, then create it if it doesn't exist, and put the files inside it.

**Comment by bahamat** [comment]
This was integrated a while back.
