### ISSUE TITLE
Add `triton instance vnc`

### ISSUE THREAD

**Issue by jasonbking** [joyent/node-triton#236]
As part of the hackathon, add support for `triton instance vnc [-p port] INST` for HVM instances.  This will start a local VNC proxy (either on the given port or a random one if not given) that will call the /:account/machines/:id/vnc cloudapi endpoint and create a web socket for the VNC traffic.

**Comment by jasonbking** [comment]
https://cr.joyent.us/#/c/3024/

**Comment by kusor** [comment]
Resolved by PR#293
