### ISSUE TITLE
`triton profile` should generate separate keys for Docker

### ISSUE THREAD

**Issue by arekinath** [joyent/node-triton#245]
Currently `triton profile` setup subcommands like `docker-setup` try to save a decrypted copy of your private key to disk for use with Docker. Since DOCKER-1005 has been rolled out very widely at this point, we can change this safely to instead generate a separate key + certificate for Docker that's signed by a main account key. This will be a safer setup from a security perspective and also a nicer user experience for people using an SSH agent with `triton`.

**Comment by arekinath** [comment]
Initial CR: https://cr.joyent.us/#/c/3860/

**Comment by bahamat** [comment]
This was implemented in 5734123.
