### ISSUE TITLE
SSHBuffer "Index out of range"

### ISSUE THREAD

**Issue by dfredell** [joyent/node-triton#247]
I upgraded from Ubuntu 17.10 to the latest Ubuntu 18.04 LTS and my triton commands are angry now.
It was all working fine before the upgrade. I also tried upgrading to the latest node-triton 6.0.0.

Doing a `triton-docker ps` results in this message and the correct output.
```
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readUInt32BE (buffer.js:1051:5)
    at SSHBuffer.readBuffer (/usr/lib/node_modules/triton/node_modules/sshpk/lib/ssh-buffer.js:45:25)
    at SSHBuffer.readString (/usr/lib/node_modules/triton/node_modules/sshpk/lib/ssh-buffer.js:56:15)
    at Request.r_cb (/usr/lib/node_modules/triton/node_modules/sshpk-agent/lib/client.js:41:22)
    at Request.state_done (/usr/lib/node_modules/triton/node_modules/sshpk-agent/lib/client-fsm.js:223:8)
    at Request.FSM._gotoState (/usr/lib/node_modules/triton/node_modules/mooremachine/lib/fsm.js:325:4)
    at FSMStateHandle.gotoState (/usr/lib/node_modules/triton/node_modules/mooremachine/lib/fsm.js:76:23)
    at Client.<anonymous> (/usr/lib/node_modules/triton/node_modules/sshpk-agent/lib/client-fsm.js:189:5)
    at emitOne (events.js:116:13)
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED             STATUS              PORTS                                                                          NAMES
.....
```

If I try doing a `triton inst get <docker>` I get the same error message but no data. 

I tried upgrading the sshpk and sshpk-agent to the latest and that didn't fix it. This issue might belong in https://github.com/joyent/node-sshpk or https://github.com/joyent/node-sshpk-agent but IDK. 

System:
```
$ uname -a
Linux bender 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
$ npm -v
5.6.0
$ nodejs -v
v8.11.1
$ sudo npm ls -g triton
/usr/lib
└── triton@6.0.0 
```

**Comment by geek** [comment]
I'm trying to reproduce the issue. What is the output when you run `$ npm -g ls mooremachine`... mine is the following after updating to the latest sshpk/agent

```
triton@6.0.0
  └─┬ sshpk-agent@1.7.0
    └── mooremachine@2.2.1
```

Also, what data center are you connecting to?

**Comment by dfredell** [comment]
I tired a fresh ubuntu docker install and wasn't able to reproduce my issue. 

> docker run -it ubuntu bash
apt update; apt install -y curl
curl -sL https://deb.nodesource.com/setup_8.x | bash -
apt-get install -y nodejs npm
npm install -g triton
curl -o /usr/local/bin/triton-docker https://raw.githubusercontent.com/joyent/triton-docker-cli/master/triton-docker && chmod +x /usr/local/bin/triton-docker && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-compose && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-docker-install


So I'm trying to uninstall my local triton and reinstall it, but it didn't help. I removed the triton with `sudo npm uninstall -g triton` and `sudo rm /usr/local/bin/triton*` Then reinstalled with:
> sudo bash -c 'curl -o /usr/local/bin/triton-docker https://raw.githubusercontent.com/joyent/triton-docker-cli/master/triton-docker && chmod +x /usr/local/bin/triton-docker && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-compose && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-docker-install'
> sudo /usr/local/bin/triton-docker-install
> sudo npm install -g triton

When installing triton I get this error a bunch and have to Ctl+C it. Then running the `npm install` again it succeeds. 
>gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/triton/node_modules/dtrace-provider/.node-gyp/8.11.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/triton/node_modules/dtrace-provider/.node-gyp"

I can reproduce the `node-gyp` issue with `docker run -it node:9.11.1-stretch npm install -g triton`

If I move my ~/.triton/profiles.d/<profile>.json out of the way I don't get this js error anymore and `triton-docker --tls ps` returns
> triton: error (Config): no such profile: <profile>
triton account: error (Config): no such profile: <profile>
triton profile: error (Config): no such profile: <profile>
CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS              PORTS                                                                          NAMES
........

I have validated that `ssh-keygen -E md5 -lf ~/.ssh/dan` returns the same MD5 as what is in ~/.triton/profiles.d/<profile>.json

**Comment by dfredell** [comment]
PS Now I appear to be getting a different js error.

>$ triton insts
events.js:188
      throw err;
      ^
Error: Unhandled "error" event. (undefined)
    at Client.emit (events.js:186:19)
    at Immediate._onImmediate (/usr/lib/node_modules/triton/node_modules/sshpk-agent/lib/client-fsm.js:313:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by dfredell** [comment]
I figured out what my issue was I had `SSH_AUTH_SOCK=/run/user/1000/keyring/ssh` set in my env. Once I did a `set SSH_AUTH_SOCK` to unset the env var the `triton insts` command worked perfectly again.
