### ISSUE TITLE
can't read from user prompts with node 8

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#252]
Using node.js 8.11.2

```
Delete firewall rule "fd4c159f"? [y/n] yevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at ReadStream.Socket._writeGeneric (net.js:764:25)
    at ReadStream.Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at ReadStream.Writable.write (_stream_writable.js:290:11)
    at ReadStream.Socket.write (net.js:707:40)
    at postInput (/opt/pkg/lib/node_modules/triton/lib/common.js:623:15)
    at ReadStream.onData (/opt/pkg/lib/node_modules/triton/lib/common.js:647:13)
    at emitOne (events.js:116:13)
```

It seems to be failing on reading the response form the `[y/n]` prompt. I ran it with debug, and it fails in exactly the same way with no additional debug output.

**Comment by marsell** [comment]
Could you give more details to help me replicate this? My attempt succeeds:

    mkukulje@bra:~/dev/node-triton$ triton fwrule ls
    SHORTID   ENABLED  GLOBAL  RULE
    46174239  false    -       FROM any TO vm 2d768acd-0c00-4d89-e2f2-fdfc39f3da84 ALLOW icmp TYPE all
    949bb2fe  false    -       FROM any TO vm 2d768acd-0c00-4d89-e2f2-fdfc39f3da84 ALLOW icmp TYPE all
    b714681e  true     -       FROM subnet 10.99.99.0/24 TO tag "smartdc_role" ALLOW tcp PORT all
    398e2a1a  true     -       FROM subnet 10.99.99.0/24 TO tag "smartdc_role" ALLOW udp PORT all
    mkukulje@bra:~/dev/node-triton$ triton fwrule rm 46174239 949bb2fe
    Delete 2 firewall rules (46174239, 949bb2fe)? [y/n] y
    Deleted rule 46174239
    Deleted rule 949bb2fe
    mkukulje@bra:~/dev/node-triton$ node --version
    v8.11.3
    mkukulje@bra:~/dev/node-triton$ uname -a
    Darwin bra 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by marsell** [comment]
I also checked this with node 8.0.0 and node-triton 6.0.0 on OSX:

    mkukulje@bra:~/tmp/node_modules/.bin$ ./triton --version
    Triton CLI 6.0.0
    https://github.com/joyent/node-triton
    mkukulje@bra:~/tmp/node_modules/.bin$ node --version
    v8.0.0
    mkukulje@bra:~/tmp/node_modules/.bin$ ./triton fwrule rm 4f8478e9 575b2ec7
    Delete 2 firewall rules (4f8478e9, 575b2ec7)? [y/n] y
    Deleted rule 575b2ec7
    Deleted rule 4f8478e9

And node 8.10.0 (though pkgsrc 18.1.0) and node-triton 6.0.0 (through npm) on SmartOS:

    [root@b350716b-0fe8-e109-804f-8278c50b3f88 ~/node_modules/.bin]# uname -a
    SunOS b350716b-0fe8-e109-804f-8278c50b3f88 5.11 joyent_20180705T212313Z i86pc i386 i86pc Solaris
    [root@b350716b-0fe8-e109-804f-8278c50b3f88 ~/node_modules/.bin]# node --version
    v8.10.0
    [root@b350716b-0fe8-e109-804f-8278c50b3f88 ~/node_modules/.bin]# ./triton --version
    Triton CLI 6.0.0
    https://github.com/joyent/node-triton
    [root@b350716b-0fe8-e109-804f-8278c50b3f88 ~/node_modules/.bin]# ./triton fwrule rm 41fbba81 8f1b78a9
    Delete 2 firewall rules (41fbba81, 8f1b78a9)? [y/n] y
    Deleted rule 8f1b78a9
    Deleted rule 41fbba81

So at this point more info is definitely needed.

**Comment by bahamat** [comment]
This seems to have been caused by some stale binary libs (or something?). I removed node-triton and re-installed and it works now.
