### ISSUE TITLE
triton instance create picks disabled image

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#258]
In the case where a new image is deployed, and then subsequently disabled (but not deleted from imgapi), `triton` will return the disabled image to `triton create <name>` and `triton image get <name>`. In both of these cases, this is almost certainly not what the user intended.

```
$ triton create debian-9 g4-highcpu-128M --network Joyent-SDC-Public -n deb9lx-test -w
triton instance create: error: error creating instance: image d3a765d6-381c-11e8-a2f0-8b4f8f1f2cca is not active
$ triton images -a | grep debian-9
63d6e664  debian-9                             20180404    P      linux    lx-dataset    2018-04-04
d3a765d6  debian-9                             20180404    PX     linux    lx-dataset    2018-04-04
$ triton create 63d6e664 g4-highcpu-128M --network Joyent-SDC-Public -n deb9lx-test -w
Creating instance deb9lx-test (222f07c5-ffee-e8a5-e578-8dbb75ae51ea, debian-9@20180404)
Created instance deb9lx-test (222f07c5-ffee-e8a5-e578-8dbb75ae51ea) in 48s
```

To address this, `triton` needs to pick the latest *active* image matching the requested name.

**Comment by bahamat** [comment]
https://cr.joyent.us/5726

**Comment by trentm** [comment]
Some callers of TritonApi.getImage do want to include inactive images, so it should be a parameter to this method.  

- `triton inst create IMAGENAME` wants only active images
- `triton image get NAME` Not sure which it should be. Debatable. I'd be inclined to keep it the same behaviour lacking a strong argument either way. Perhaps, if important enough, a separate change could add a `triton image get -a,--all NAME` to include all image states, and change the default to limit to active images. 
- `triton image wait NAME` to wait for an image to be fully created (state=creating, per https://images.joyent.com/docs/#manifest-state) wants to include inactive images.
- `triton image delete NAME` should include an inactive image.
- the call to getImage in `triton inst ssh` perhaps wants to include looking up info on the image of a named bastion image even if it is now disabled. Debatable.

**Comment by trentm** [comment]
Hrm... having `triton image get NAME` potentially show a diff image to `triton inst create NAME ...` is annoying (granted this should be a rare case).

@bahamat Another option if just for this case in JPC is to *delete* those images or make them private. Then they are just out of the picture for users.

**Comment by trentm** [comment]
`triton image list` already has `-a,--all`, so I don't think adding that to `triton image get NAME` is weird.

**Comment by bahamat** [comment]
Regardless of what we do in JPC, it's possible that any datacenter might have newer, disabled images. And this is really the case I'm concerned about.

I feel strongly that `triton create NAME` should pick something active, but `image wait NAME` and `image delete NAME` have convinced me that it should always just return only active images when a name is specified.

I've amended the cr with this behavior. We can still discuss other changes if you like.

**Comment by trentm** [comment]
@bahamat Alternative proposed fix: https://cr.joyent.us/#/c/5727/  Are you able to review that?

**Comment by trentm** [comment]
Oops. I used the wrong issue number. I'll correct that.

**Comment by trentm** [comment]
triton@7.0.0 published with ^^
