### ISSUE TITLE
config.js validateProfile is confused about how to be insecure

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-triton#263]
In `validateProfile` of `config.js` we have:

```
        assert.optionalBool(profile.insecure,
            profile.name === 'env' ? 'TRITON_INSECURE or SDC_INSECURE'
: 'profile.insecure');
```

However, this is the only occurrence of `TRITON_INSECURE`.  Everywhere else uses `TRITON_TLS_INSECURE`

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/6116/

**Comment by trentm** [comment]
This will be in the next release (I belive there are coming rbac-y changes, so I won't cut a release just for this).
