### ISSUE TITLE
node-triton fails to resolve host when a CNAME

### ISSUE THREAD

**Issue by bhechinger** [joyent/node-triton#285]
If the hostname for cloudapi is a CNAME node-triton fails to connect to it:

```
$ triton ssh dns-01
triton instance ssh: error (ENOTFOUND): getaddrinfo ENOTFOUND triton-api.example.net
```

However if the hostname for cloudapi is an A record (or also placed in /etc/hosts) it functions correctly:

```
$ triton ls
SHORTID   NAME    IMG                 STATE    FLAGS  AGE
f5dfeae0  dns-02  base-64-lts@19.4.0  running  -      3h
696e52cd  dns-01  base-64-lts@19.4.0  running  -      3h
```

**Comment by bahamat** [comment]
I think there's an issue with your DNS settings. Joyent has used a cname to cloudapi for years without problems.
