### ISSUE TITLE
triton ssh command not aware of "ubuntu" login for ubuntu-certified images

### ISSUE THREAD

**Issue by chorrell** [joyent/node-triton#3]
`triton ssh INSTANCE_NAME` will fail on an instance based on ubuntu-certified with the following error:

```
[christopher@JoyentMacBookPro ~/GitHub/node-triton]$ triton ssh ubuntu-certified-14.04-20150805
Warning: Permanently added '8.12.42.20' (ECDSA) to the list of known hosts.
Please login as the user "ubuntu" rather than the user "root".


Connection to 8.12.42.20 closed.
```

**Comment by dillona** [comment]
I put up [a change](https://cr.joyent.us/1171) that handles this using the image cache. In addition, I extended the TTL to one hour when retrieving specific images. On my system this results in no measurable performance difference for this change as long as the json file is in the cache

**Comment by trentm** [comment]
This'll be in 5.0.0 when we release that. Thanks, @dillona!
