### ISSUE TITLE
source <(triton completion) doesn't work on Mac 10.11.1 bash 3.2.57(1)

### ISSUE THREAD

**Issue by lloydde** [joyent/node-triton#31]
`source <(triton completion)` doesn't work on Mac 10.11.1 bash 3.2.57(1). It is documented in README.md .

It worked as expected on lx ubuntu-14.04@20150819 and when `triton completion >> ~/.bashrc` on Mac.

~~~
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B17c
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
~~~

**Comment by trentm** [comment]
I think to install the completions one really should consider writing it to one's `bash_completion.d` dir. I've updated the README and `triton completion -h` notes to do this.  I think that's good enough for this ticket. Please re-open if you feel not.
