### ISSUE TITLE
Wrong CLI_CONFIG_DIR when XDG_CONFIG_HOME is set

### ISSUE THREAD

**Issue by teutat3s** [joyent/node-triton#311]
Just noticed this while testing with my XDG setup, this line
https://github.com/joyent/node-triton/blob/304725b93fc1ef9605705f21cca77986fcdc1b88/lib/constants.js#L46

should be
```
CLI_CONFIG_DIR = mod_path.resolve(process.env.XDG_CONFIG_HOME, 'triton');
```

without the `.`, because `.config` is the hidden `XDG_CONFIG_HOME` directory usually, then all sub-directories get non-hidden names.

Example for reference here: https://github.com/joyent/node-triton/pull/291/files#diff-602f56bb692d9bf3bdc5fef3d75d5fa33fe841c3d21ca46294bb6fdaf0785d0cR54

**Comment by bahamat** [comment]
Fixed in #312
