### ISSUE TITLE
`triton list` alias for instances

### ISSUE THREAD

**Issue by lloydde** [joyent/node-triton#34]
Feature request: `triton list` alias for `triton instances` as i is really crowded.

~~~
$ triton i
image           images          img             imgs            info            inst
instance        instance-audit  instances       insts
~~~

**Comment by bahamas10** [comment]
I fully support this alias

@trentm thoughts? I think "instances" are first-class in the `node-triton` world, so telling it to "list" would make sense for it to show instances

**Comment by trentm** [comment]
+1
