### ISSUE TITLE
Need to differentiate kvm vs lx in "triton images" output

### ISSUE THREAD

**Issue by lloydde** [joyent/node-triton#35]
Need to differentiate kvm vs lx in "triton images" output

~~~
$ triton images | grep -E 'SHORTID|ubuntu'
SHORTID   NAME                                 VERSION     STATE   FLAGS  OS       PUBDATE
e28711b3  ubuntu-certified-12.04               20140227    active  P      linux    2014-02-27
fe5aa6c0  ubuntu-certified-12.04               20140408    active  P      linux    2014-04-08
df165dad  ubuntu-certified-14.04               20140416    active  P      linux    2014-04-16
7735fbba  ubuntu-certified-14.04               20140519    active  P      linux    2014-05-19
0fd57f23  ubuntu-certified-12.04               20140519    active  P      linux    2014-05-19
f21af273  ubuntu-certified-12.04               20140608    active  P      linux    2014-06-08
286b0dc0  ubuntu-certified-14.04               20140608    active  P      linux    2014-06-08
202d0d26  ubuntu-certified-14.04               20140729    active  P      linux    2014-07-29
6c970fa8  ubuntu-certified-12.04               20140806    active  P      linux    2014-08-06
d0fb3c79  ubuntu-certified-12.04               20140926    active  P      linux    2014-09-26
c841e585  ubuntu-certified-14.04               20140926    active  P      linux    2014-09-26
01a24b88  ubuntu-certified-12.04               20140929    active  P      linux    2014-09-29
5f67e820  ubuntu-certified-14.04               20140929    active  P      linux    2014-09-29
47c62485  ubuntu-certified-14.10               20141022.3  active  P      linux    2014-10-22
be16f02b  ubuntu-certified-12.04               20150127    active  P      linux    2015-01-27
c864f104  ubuntu-certified-14.04               20150225.2  active  P      linux    2015-02-25
415e39e6  ubuntu-certified-12.04               20150225.1  active  P      linux    2015-02-25
430da066  ubuntu-14.04                         20150415    active  P      linux    2015-04-15
a21a64a0  ubuntu-14.04                         20150601    active  P      linux    2015-06-01
5a0145ee  ubuntu-14.04                         20150618    active  P      linux    2015-06-18
7a56eecc  ubuntu-14.04                         20150625    active  P      linux    2015-06-25
0bd891a8  ubuntu-14.04                         20150629    active  P      linux    2015-06-29
506bd05d  ubuntu-certified-12.04               20150709    active  P      linux    2015-07-09
143e254a  ubuntu-certified-14.04               20150708    active  P      linux    2015-07-09
a41ffcbc  ubuntu-certified-14.10               20150708    active  P      linux    2015-07-09
ead4ff68  ubuntu-14.04                         20150724    active  P      linux    2015-07-24
b33d4dec  ubuntu-certified-15.04               20150807    active  P      linux    2015-08-08
c8d68a9e  ubuntu-14.04                         20150819    active  P      linux    2015-08-19
~~~

I can't tell which of those are Lx-brand and which are kvm images. 

**Possible Solutions**

For sdc-adminui listing, I'm going to prepend "kvm" to the OS of zvol ones. Alternatively, you could introduce another column.

**Comment by askfongjojo** [comment]
We can't re-purpose the OS column as you can have windows/kvm, freebsd/kvm, etc.
The unfortunately/poorly-named attribute for this purpose is "type", which returns either "smartmachine" or "virtualmachine". We can expose that and hide pubdate to make space for it. Down the road, it'll be good to be able to rename the type field and values to something better but it can be done only if we support versioning.

**Comment by misterbisson** [comment]
It would not be ok to overload any existing column for that purpose. A new column is required.

**Comment by trentm** [comment]
In the TODO.txt I'd had this: `*type*: cloudapi changes to clarify: LX, docker, smartos, kvm instances`

I don't have a solid proposal yet. Cloudapi's renaming of "type" values sucks. Would *could* have a `triton` client-side translation to a `typ` or `kind` column that had nicer values: container/vm or lx/smartos/kvm or whatever.

**Comment by misterbisson** [comment]
I'd like to make sure we talk about three "types" of compute instances:

> ### Docker containers

> Docker containers on Triton can run images from a variety of registries, including public and private. See detailed documentation for connecting to those registries in [containers](https://docs.joyent.com/public-cloud/containers) → [Docker](https://docs.joyent.com/public-cloud/containers/docker) → [registries](https://docs.joyent.com/public-cloud/containers/docker/registries).

> ### Infrastructure containers

> Infrastructure containers running container-native Linux and SmartOS, or pre-configured installations of up-stack software such as databases or load balancers offer the advantage of bare-metal performance with the elasticity of containers and security that's only available using Triton.

> See information about available images, including bare operating systems and configured applications in [containers](https://docs.joyent.com/public-cloud/containers) → [infrastructure containers](https://docs.joyent.com/public-cloud/containers/infrastructure) → [images](https://docs.joyent.com/public-cloud/containers/infrastructure/images). Also see details about creating a [custom container-native image](https://docs.joyent.com/public-cloud/containers/infrastructure/images/creating).

> ### Hardware virtual machines

> Not every workload can be deployed as a container. We also offer images for KVM-based hardware virtual machines to support the broadest range of legacy or special purpose operating systems.

> Available images include [FreeBSD](/images/hardware-virtual-machine/freebsd), [Linux](/images/hardware-virtual-machine/linux) (not container-native), and [Windows](/images/hardware-virtual-machine/windows).

Specifically, we don't want to differentiate between "lx" and "smartos" instances, as the way they fit into people's infrastructure needs is identical: they're infrastructure containers.

**Comment by lloydde** [comment]
@askfongjojo , @misterbisson what are the scenarios of concerns for the the ascii output prepending "kvm" for this *new* *tool*? "kvm windows" and "kvm bsd" seem fine. Seems like an elegant hack. Another column is not particularly human-friendly particularly when the collision is only currently in linux; docker images all are named "docker*".

--

1. OT: is there recent discussion about naming new kvm linux images with kvm in the name? The dropping of lx for ubuntu has caused much fun.

2. OT: is there a cloudapi jira related to a field for the three "types": inf containers, docker, and kvm?

3. OT: for docker images any plan to make human friendly column exposing the docker image name? I'd like to incorperate this in adminui search if possible.

**Comment by trentm** [comment]
@lloydde Re: docker images: The get the "friendly" docker name is user specific and needs to talk to sdc-docker to get that info. That docker images live in imgapi is (at least currently) an implementation detail.

**Comment by trentm** [comment]
@misterbisson Suggestions for the short names for those three types/kinds/flavours of instances?

**Comment by lloydde** [comment]
> needs to talk to sdc-docker to get that info
Prime!

**Comment by misterbisson** [comment]
@trentm, re: short names. It depends on how short you want.

Instance types of different lengths:

- Docker c. 
- Infrastructure c.
- Hardware VM

- Docker c. 
- Infrastruct. c.
- Hardware VM

- DC
- IC
- HVM

Side question:

- Can we use :copyright: to indicate "container?"
- What about ![amphora](http://emojipedia-us.s3.amazonaws.com/cache/56/68/5668a23a0738003afe0825f3369b737c.png) (the amphora symbol)?

More seriously, I should point out that I use "hardware virtual machine" instead of just "virtual machine" to distinguish the instance type from our language in the admin UI and CloudAPI where we call every instance type a "machine."

**Comment by trentm** [comment]
Per discussion on PUBAPI-1161 (https://smartos.org/bugview/PUBAPI-1161), just going to expose the 'type' field in default `triton images` output. See write up on output changes (for this and `triton instances` changes that are similar) here: https://gist.github.com/trentm/62f78bb5141e75ec6abe

**Comment by trentm** [comment]
This will be in triton@4.1.0 (probably later today)
