### ISSUE TITLE
undefined image name and version when passing complete image uuid in create request

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-triton#36]
A bit of a corner case:
$ triton create --name=from-lx-image 4dce9fd4-1637-419b-9109-ca570e2239d6 t4-standard-1G 
Creating instance from-lx-image (2057db45-8a13-4dab-fd53-a34f82c77b13, undefined@undefined, t4-standard-1G)

**Comment by trentm** [comment]
Don't recall exactly, but I think broken in commit 44ce942d9795e70a1ab7187a3e2c19fc09d36c8f for #25.

**Comment by bahamas10** [comment]
https://github.com/joyent/node-triton/issues/29 that's what this issue was referring to... i'll work on it today.

**Comment by askfongjojo** [comment]
Ah ok. Let me close it as dup then.
