### ISSUE TITLE
'triton ls' alias for insts

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#45]
Similar to #44.

**Comment by bahamat** [comment]
If `ls` is going to be added, might be worth adding `list` as well, although I would argue `ps` (à la docker) is going too far.

**Comment by misterbisson** [comment]
But if people expect `ps` from Docker...

**Comment by jclulow** [comment]
We will absolutely not be continuing the `ps` _lunacy_.

**Comment by trentm** [comment]
Let's leave `ps` to a `jocker ps` command. ;)

**Comment by trentm** [comment]
This ticket is a dupe of  #34
