### ISSUE TITLE
Brew install support for Mac OS X

### ISSUE THREAD

**Issue by misterbisson** [joyent/node-triton#47]
I'd love to be able to tell Mac users to install `triton` using a command like `brew install triton` and be done. Many of us are using `brew` to install `node` and `npm`, so the package dependencies are already there, and the win in convenience is huge.

**Comment by trentm** [comment]
Perhaps:

```
brew install npm
npm install -g triton
```

;)


Seriously tho, do you install other npm modules using brew (it would help to look at prior art)? I kinda feel that triton is *npm's* domain. Having package managers handle another package manager's job results in tears, in my totally biased experience. I welcome others' experiences tho.

**Comment by bahamat** [comment]
Homebrew has a policy to not package language modules.

<https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-try-hard-to-avoid-dupes-in-homebrewhomebrew>

> Stuff that comes with OS X or libraries that are provided by RubyGems, CPAN or PyPi should not be duplicated.

This extends to (though not explicitly mentioned) haskell/cabal and node/npm.

**Comment by trentm** [comment]
there you go

**Comment by lloydde** [comment]
The wording there is a little tricky. It describes "libraries" though I've seen Ruby and PyPi installable "applications" rejected. Though there is also apps like youtube-dl which is all python. Generally, it seems it has to be popular to be accepted.

I suspect you wouldn't get it in to homebrew at this stage.
