### ISSUE TITLE
update deps to get a bunyan > dtrace-provider that works with node v4.2

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#51]

**Comment by trentm** [comment]
commit 37dd71b is a start

**Comment by trentm** [comment]
I published smartdc-auth@2.1.7 (with commit https://github.com/joyent/node-smartdc-auth/commit/01ec1660af16f1b7d924b66e971011f6ab9d0948 to get updated bunyan)

**Comment by trentm** [comment]
published as triton@2.1.4

**Comment by bahamat** [comment]
LGTM. No issues installing node-triton fresh, no errors about dtrace-provider.
