### ISSUE TITLE
`triton create -m,--metadata` etc. for adding metadata on instance creation

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#59]
This is a proposal for supporting adding metadata to the created instance:

    triton create IMG PKG -d METADATA           # short opt
    triton create IMG PKG --metadata METADATA   # long opt

where METADATA is:

- JSON if the first char is '{'
- key/value pair of the form "key=value", where `value` is lightly interpreted
  as JSON: boolean (`true` or `false`), number, or a string.
- '@FILE' loads JSON and/or key/value pairs from file FILE

The '-d,--metadata' option can be used multiple times.

Some metadata keys are a little special. E.g. user-script, if used, would
commonly have multiple lines, and needs to be JSON-encoded. That one
justifies a separate option, at least we think:

    triton create IMG PKG -d 'user-script=#!/bin/sh\n...'  # not very handy
    triton create IMG PKG --user-script foo.sh

If the same key is used, last one wins (but a warning is emitted). This includes
re-use of 'user-script' in '--user-script' and '-d' option usage.

**Comment by chorrell** [comment]
user-data  might need a separate option as well for similar reasons (it can multiline, like potentially being config file contents or something similar).

**Comment by trentm** [comment]
@chorrell Does `sdc-createmachine` even have an option for that?  I've never used user-data. It isn't in cloudapi docs. :|

**Comment by chorrell** [comment]
@trentm no sdc-createmachine support, but it is noted here http://eng.joyent.com/mdata/datadict.html

All KVM images built in the last maybe 2+ years should have support for it; all the smartos and lx-brand images definitely do. 

The cloud api docs need a bit of attention. They mention user-script but it's kind of burried and lacking detail.

**Comment by jclulow** [comment]
Can we use the short option `-m` for `--metadata` instead of `-d`?

Also, I'd like to have `--metadata-file` as well, which could be `-M`.  This one would accept `-M keyname=somefile.txt`, allowing a local file to be set as an arbitrary metadata key.

I think it'd be fine to keep using `--script`, as `sdc-createmachine` used to do, instead of the wordier `--user-script`.  I wouldn't provide a special option for `user-data`; `-M` seems like it would be enough for that.

**Comment by trentm** [comment]
> Can we use the short option -m for --metadata instead of -d?

Sure. Using that.

> Also, I'd like to have --metadata-file as well, which could be -M. This one would accept -M keyname=somefile.txt, allowing the contents of a local file to be set as an arbitrary metadata key.

Sure. Doing that too.

> I think it'd be fine to keep using --script, as sdc-createmachine used to do, instead of the wordier --user-script. I wouldn't provide a special option for user-data; -M seems like it would be enough for that.

I'm leaning to the wordier one because that is the name of the key and I think that helps make the mental connection. There is tab completion to help with the wordiness. If we find it is commonly used and annoying to have the wordiness we could consider a '-s' or '-S' short option. Do you can strongly against `--user-script FILE`?

**Comment by jclulow** [comment]
I don't feel like `--user-script` makes more obvious what it is or what it does.  I get that it's the name of the underlying metadata key, and I think you could mention that fact in the help message -- but it seems like something of an implementation detail.  I think people would be more likely to look at `--script` and think that it's just a script that gets run in the instance.

**Comment by trentm** [comment]
k

**Comment by trentm** [comment]
triton@3.3.0 published with this
