### ISSUE TITLE
"triton images" with a filter should not be cached

### ISSUE THREAD

**Issue by jclulow** [joyent/node-triton#63]
When I run `triton insts`, the `IMG` column displays the name of the image from which the instance was created; e.g., `base@13.1.0`.  If I use `triton images`, I get of all the images that the data centre will let me see.

If I then run `triton images name=~lts`, I get a list of images that match the pattern `*lts*`.  When I run `triton insts` again, only images that matched the pattern are printed by name; the rest are printed by UUID.  If I run `triton images` again, without a filter, `triton insts` will once again print image names for everything.

It seems like running `triton images` with a filter is replacing the image cache with an incomplete picture of the world.  Perhaps we should only cache filterless runs of `triton images`?

**Comment by trentm** [comment]
This is fixed in triton@3.4.2
