### ISSUE TITLE
support instance renaming

### ISSUE THREAD

**Issue by jclulow** [joyent/node-triton#64]
CloudAPI appears to allow the user to rename their instance (i.e. change the value of `alias`).  This will become more important as users begin to use the upcoming Triton CNS.  This operation is supported by the CloudAPI [RenameMachine](https://apidocs.joyent.com/cloudapi/#RenameMachine) endpoint, as wrapped in the old world by [sdc-renamemachine](https://github.com/joyent/node-smartdc/blob/master/bin/sdc-renamemachine).

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/828

**Comment by trentm** [comment]
This'll be in the release after 4.14.2 (probably 4.15).

#146 added to eventually get a '-w,--wait' option on this.
