### ISSUE TITLE
JSON output on collection commands

### ISSUE THREAD

**Issue by cehoffman** [joyent/node-triton#70]
The JSON output for a command like `triton inst ls -j` is broken for piping to other JSON tools. The output is individual JSON objects instead of an array of JSON objects.

Current:
~~~
$ triton inst ls -j
{...}
{...}
{...}
~~~

Propose:
~~~
$ triton inst ls -j
[
{...},
{...},
{...}
]
~~~

**Comment by trentm** [comment]
@cehoffman What JSON tools? trentm/json for example can handle this with `json -ga ...`.  The idea with newline-separated JSON is that while it *does* force usage (tools, libraries) to change from "parse a single JSON document", it scales much better. Streaming is the only sane answer when lists get really big: e.g. 100s or 1000s of instances, images, etc.

Happy to re-open and consider adding some "-J, --really-really-a-single-JSON-doc" option if there is a strong case for using tools that can't cope.

**Comment by cehoffman** [comment]
I was looking specifically at the json tool since I was coming from smartdc and didn't comprehend the `-g` option apparently. I hadn't seen anywhere else demonstrating that sort of usage. Agree streaming is the better option and happy to find how to consume it.
