### ISSUE TITLE
want `triton image` to still return image details even when it is not in 'active' state

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-triton#72]
Current with an image in inactive state, I'd get this:
$ triton image 46a24e03-bdde-e611-ae08-9e5770278d7a
triton image: error: image 46a24e03-bdde-e611-ae08-9e5770278d7a is not active

It should work like sdc-getimage and return the image details regardless of its state.

**Comment by trentm** [comment]
this'll be in triton@4.3.0
