### ISSUE TITLE
`triton instance list` filtering on tags

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#74]
Given that you filter VM instances with `triton` already as follows:

```
triton insts [FILTERS...]
```

Examples:

```
triton insts os=linux
triton insts state=provisioning
triton insts state=provisioning docker=true
```

What would you suggest/prefer for syntax for filtering on _tags_?

```
triton insts -t foo=bar     # somewhat reasonable, but not like other filters
triton insts --tag foo=bar

triton insts tag.foo=bar    # like CloudAPI and other CLI filters, but weird
triton insts tags.foo=bar
triton insts tag:foo=bar    # slightly less weird, but inconsistent
triton insts tag=foo:bar    # note `triton create -t foo=bar ...`, inconsistent with creation
```

What they would look like together:

```
triton insts state=provisioning tag.foo=bar
triton insts state=provisioning -t foo=bar
triton insts state=provisioning tag:foo=bar
```

Nothing is fully satisfying.

I'm leaning towards supporting:

```
triton insts ... tag.foo=bar     # and
triton insts ... tags.foo=bar
```

**Comment by bahamas10** [comment]
this is an annoying issue... I think because it will ultimately act like a filter, it should be the `tag.foo=bar` notation.  It'll look and work just like a filter, just prefixed with `tag.`

**Comment by trentm** [comment]
See also internal ticket TOOLS-1872.

+1 to `triton ls tag.foo=bar ...` syntax.

**Comment by trentm** [comment]
CR: https://cr.joyent.us/#/c/2682/
