### ISSUE TITLE
locality flag/property at creation (far/near as in sdc-createmachine)

### ISSUE THREAD

**Issue by pannon** [joyent/node-triton#82]
Would be nice to have a locality flag at creation (far/near as in sdc-createmachine).

**Comment by trentm** [comment]
Agreed. That is one of the missing (the last?) flags for full coverage of `triton instance create`.

**Comment by pannon** [comment]
Yes, seems that way - this is the only missing part in `triton instance create`.

**Comment by misterbisson** [comment]
:+1: 

Also, thank you for your patience with my button pressing here.

**Comment by trentm** [comment]
This is now in triton v4.10.0: https://github.com/joyent/node-triton/blob/master/CHANGES.md#4100
