### ISSUE TITLE
PTY allocation request failed on channel 0

### ISSUE THREAD

**Issue by cmosetick** [joyent/node-triton#85]
Just testing this out, and on my second test, this is what I get when trying to ssh to an instance.

```
triton ssh test2
PTY allocation request failed on channel 0
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0 x86_64)

                   Instance (Ubuntu 14.04 20151005)
                   https://docs.joyent.com/images/container-native-linux

stdin: is not a tty
```
I have to control-c to get back to my local shell

**Comment by jclulow** [comment]
It would be good to know more about your environment, e.g.:

- OS version
- Node version
- `triton` version

**Comment by cmosetick** [comment]
OS: Mac OS X El Capitan, 10.11.2
Node version: v5.5.0
`triton` version: 4.4.1
```
triton info
login: <removed>
name: Chris Mosetick
email: <removed>
url: https://us-sw-1.api.joyent.com
totalDisk: 23.8 GiB
totalMemory: 976.5 MiB
instances: 1
    stopped: 1

**Comment by pfmooney** [comment]
See also: [OS-5101](https://smartos.org/bugview/OS-5101) and [OS-5092](https://smartos.org/bugview/OS-5092)

**Comment by cmosetick** [comment]
I've been unable to reproduce this issue again, so feel free to close it.

**Comment by trentm** [comment]
can re-open if hitting it again.
