### ISSUE TITLE
datacenters subcommand not compatible with OpenSSH 7

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#87]
````
$ triton datacenters                                                         
triton datacenters: error: Fingerprint format is not supported, or is invalid: fingerprint = SHA256:XXXX
SHA256:XXXX
````

**Comment by bahamat** [comment]
Nm, this was my mistake.

**Comment by foxx** [comment]
For anyone else having this problem, this is the reason;

https://github.com/joyent/node-smartdc/pull/77/files

In short, use the following command to get the correct fingerprint;

```
ssh-keygen -E md5 -lf  ~/.ssh/id_rsa.pub  | awk '{print $2}'
```

**Comment by arekinath** [comment]
@foxx This is not the problem in any recent versions. If you are using the latest version of `triton`, SHA256 format fingerprints are accepted and work fine, and there is no need to use that form of the command. On older versions (pre March or so this year) you may have to do this, though.
